# .github/workflows/ci.yml
name: CI Workflow

# Trigger the workflow on push to dev and main, and on pull requests to these branches
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:

    # Use the latest Ubuntu runner for the build
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3
      
      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your .NET version
      
      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Step 4: Build the application
      - name: Build the application
        run: dotnet build --no-restore --configuration Release
      
      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Build and Push User Service Docker image
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}  # Use the GitHub Secret
          APP_UID: 1000
        run: |
          docker build --build-arg DB_CONNECTION_STRING=$DB_CONNECTION_STRING -t ${{ secrets.DOCKER_USERNAME }}/user-services:v1 ./CareerMatch.UserServices
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/user-services:v1

      - name: Run the container
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          docker run -d --name user-service -e DB_CONNECTION_STRING=$DB_CONNECTION_STRING -p 8082:80 ${{ secrets.DOCKER_USERNAME }}/user-services:v1